import type { ChoiceQuestion } from "@typesafe-ai/sdk";
import { describe, expect, it } from "vitest";
import { buildStep } from "../../src/fast/policy.js";
import { extractSpans } from "../../src/task.js";
import { el, obs } from "./fakes.js";

/**
 * Task wording from the review rounds: each entry names the value that a field's value head must offer in a run without
 * a text source (the CLI), and the wrong values that no head may offer (CLI or plugin). A rule change for one wording
 * broke another in earlier rounds; this table keeps every one of them.
 * - line: a single-line text field; text: a multiline field; search: a search box (it takes an exact value).
 * - has: the CLI head offers it. pluginHas: the plugin head (with generate) offers it too.
 * - not: no head offers it (CLI or plugin). pluginNot: the plugin head does not offer it.
 * - notAlone: a wrong value that must not be the only choice. A head (CLI or plugin) that offers it also offers every
 *   `has` value: "Review" of "Review and approve Q3 budget" is offered only with the full name.
 * - first: the first value comes before the second in the CLI head. cliNone: the CLI head offers no task value, so the
 *   run asks for the value.
 */
type Kind = "line" | "text" | "search";
interface Want { has?: string[]; pluginHas?: string[]; not?: string[]; notAlone?: string[]; first?: [string, string]; pluginNot?: string[]; cliNone?: boolean }
const CORPUS: [string, string, Kind, Want][] = [
  ["Rename the file to budget and click Save", "Name", "line", {"has":  ["budget"], "not":  ["budget and click Save"]}],
  ["Create a folder named Tax Receipts 2026 and click Create", "Name", "line", {"has":  ["Tax Receipts 2026"], "not":  ["Tax Receipts 2026 and click Create"]}],
  ["Add a label named urgent and click Add", "Name", "line", {"has":  ["urgent"], "not":  ["urgent and click Add"]}],
  ["Set the title to weekly sync and press Enter", "Title", "line", {"has":  ["weekly sync"], "not":  ["weekly sync and press Enter"]}],
  ["Set the subject to lunch plans and hit Send", "Subject", "line", {"has":  ["lunch plans"], "not":  ["lunch plans and hit Send"]}],
  ["Rename the doc to budget review and click on Save", "Name", "line", {"has":  ["budget review"]}],
  ["Rename the workflow to nightly sync job and click Save", "Name", "line", {"has":  ["nightly sync job"]}],
  ["Change the status message to out of office and save changes", "Status", "line", {"has":  ["out of office"]}],
  ["Rename the channel to general chat and go back", "Name", "line", {"has":  ["general chat"]}],
  ["Set the date to 15 September 2026 and click Update", "Date", "line", {"has":  ["15 September 2026"], "not":  ["15 September 2026 and click Update"]}],
  ["Set the title to Weekly sync and click Save", "Title", "line", {"has":  ["Weekly sync"]}],
  ["Save it as budget review and close it", "Name", "line", {"has":  ["budget review"]}],
  ["Rename the file to budget and click save", "Name", "line", {"has":  ["budget"], "not":  ["budget and click save"]}],
  ["Set the title to weekly sync and press enter", "Title", "line", {"has":  ["weekly sync"]}],
  ["Rename the artifact to Q3 Budget Review and save it", "Name", "line", {"has":  ["Q3 Budget Review"]}],
  ["Change the project instructions to Always answer in English and save", "Instructions", "text", {"has":  ["Always answer in English"]}],
  ["Create a project called Apollo Launch and invite Ann Lee", "Name", "line", { has: ["Apollo Launch"], not: ["Apollo Launch and invite Ann Lee"] }],
  ["Type hello and send it to Ann", "Message", "text", { has: ["hello", "hello and send it to Ann"], pluginHas: ["hello"], first: ["hello", "hello and send it to Ann"], not: ["hello and send it"], notAlone: ["Ann"] }],
  ["Rename the artifact to budget review and save it", "Name", "line", {"has":  ["budget review"]}],
  ["Create a group named Design team and invite Ann Lee to the channel", "Name", "line", {"has":  ["Design team"]}],
  ["Look up weather in Paris and press Enter", "Search", "search", {"has":  ["weather in Paris"], "not":  ["weather in Paris and press Enter"]}],
  ["Search projects for licious and open it", "Search", "search", {"has":  ["licious"]}],
  ["Open the command bar, search for Q3 Roadmap and open the artifact", "Search", "search", {"has":  ["Q3 Roadmap"]}],
  ["Type hello and press Enter", "Message", "text", {"has":  ["hello"], "not":  ["hello and press Enter"]}],
  ["Write thanks and send it", "Message", "text", {"has":  ["thanks"], "not":  ["thanks and send it"]}],
  ["Type lgtm and click Comment", "Comment", "text", {"has":  ["lgtm"], "not":  ["lgtm and click Comment"]}],
  ["Type ok and send", "Message", "text", {"has":  ["ok"], "not":  ["ok and send"]}],
  ["Write sounds good and click Send", "Message", "text", {"has":  ["sounds good"]}],
  ["Reply with thanks and send it", "Reply", "text", {"has":  ["thanks"], "not":  ["thanks and send it"]}],
  ["Type hello team and send the message", "Message", "text", {"has":  ["hello team"], "not":  ["hello team and send the message"]}],
  ["Reply with ok and close it", "Reply", "text", {"has":  ["ok"], "not":  ["ok and close it"]}],
  ["Reply with Done and mark it resolved", "Reply", "text", {"has":  ["Done"]}],
  ["Respond with Approved and close the ticket", "Reply", "text", {"has":  ["Approved"]}],
  ["Reply with Noted and archive the email", "Reply", "text", {"has":  ["Noted"]}],
  ["Comment with fixed in v2 and close it", "Comment", "text", {"has":  ["fixed in v2"]}],
  ["Leave a comment with nice work and close the issue", "Comment", "text", {"has":  ["nice work"]}],
  ["Reply with got it and close the tab", "Reply", "text", {"has":  ["got it"]}],
  ["Answer with yes and go to the next question", "Answer", "text", {"has":  ["yes"]}],
  ["Post a comment with ship it and approve the PR", "Comment", "text", {"has":  ["ship it"]}],
  ["Reply with thanks and confirm it", "Reply", "text", {"has":  ["thanks"], "not":  ["thanks and confirm it"]}],
  ["Reply with happy to help and share the doc", "Reply", "text", {"has":  ["happy to help"]}],
  ["Comment with LGTM and approve it", "Comment", "text", {"has":  ["LGTM"], "not":  ["LGTM and approve it"]}],
  ["Type Berlin and select the first suggestion", "City", "line", {"has":  ["Berlin"], "not":  ["Berlin and select the first suggestion"]}],
  ["Enter Berlin and select the first suggestion", "City", "line", {"has":  ["Berlin"], "not":  ["Berlin and select the first suggestion"]}],
  ["Type ann and choose the first match", "Assignee", "line", {"has":  ["ann"], "not":  ["ann and choose the first match"]}],
  ["Type Ann and select Ann Lee", "Assignee", "line", {"has":  ["Ann"], "not":  ["Ann and select Ann Lee"]}],
  ["Fill the Message field with hello and select the general channel", "Message", "text", {"has":  ["hello"]}],
  ["Open the post and tag it with urgent and assign it to Ann", "Tag", "line", {"has":  ["urgent"]}],
  ["Edit the post title as hello world and update it", "Title", "line", {"has":  ["hello world"]}],
  ["Open the post settings and set the slug as my-first-post and close the dialog", "Slug", "line", {"has":  ["my-first-post"]}],
  ["Filter the chat with invoice and open the first result", "Filter", "search", {"has":  ["invoice"]}],
  ["Save the text as budget notes and close it", "Name", "line", {"has":  ["budget notes"]}],
  ["Save the chat transcript as Weekly notes and open it", "Name", "line", {"has":  ["Weekly notes"]}],
  ["Mark the message with follow up and move it to Later", "Label", "line", {"has":  ["follow up"]}],
  ["Open the message and label it as Important and archive it", "Label", "line", {"has":  ["Important"], "not":  ["Important and archive it"]}],
  ["Share the post with Ann and notify her", "Share with", "line", {"has":  ["Ann"], "not":  ["Ann and notify her"]}],
  ["Rename the channel to Show and Tell", "Name", "line", {"has":  ["Show and Tell"]}],
  ["Create a playlist called Hit and Run", "Name", "line", {"has":  ["Hit and Run"]}],
  ["Set the subject to Budget and schedule update", "Subject", "line", {"has":  ["Budget and schedule update"]}],
  ["Create an event named Save the Date and Send Invites", "Name", "line", {"has":  ["Save the Date and Send Invites"]}],
  ["Set the filter name to closed and open issues", "Name", "line", {"has":  ["closed and open issues"], "not":  ["closed"]}],
  ["Set the button label to \"Save and Close\"", "Label", "line", {"has":  ["Save and Close"]}],
  ["Set the title to 'Plan and Share' and save", "Title", "line", {"has":  ["Plan and Share"]}],
  ["Create a folder named Copy and Paste Guides", "Name", "line", {"has":  ["Copy and Paste Guides"]}],
  ["Create a project named Build and Run Tests", "Name", "line", {"has":  ["Build and Run Tests"]}],
  ["Create a folder named Media and press releases", "Name", "line", {"has":  ["Media and press releases"]}],
  ["Rename the folder to Media and press kits", "Name", "line", {"has":  ["Media and press kits"]}],
  ["Create a report named Opens and click rate", "Name", "line", {"has":  ["Opens and click rate"]}],
  ["Create a task named Draft blog post and press release", "Name", "line", {"has":  ["Draft blog post and press release"], "not":  ["Draft blog post"]}],
  ["Create an objective called Grow revenue and hit 1M ARR", "Name", "line", {"has":  ["Grow revenue and hit 1M ARR"], "not":  ["Grow revenue"]}],
  ["Create a task titled Review and submit expense report", "Title", "line", {"has":  ["Review and submit expense report"]}],
  ["Set max turns to 250 and maximum output tokens to 8000", "Max turns", "line", {"has":  ["250"]}],
  ["Type we will review and approve it in the comment box", "Comment", "text", {"has":  ["we will review and approve it"], "not":  ["we will review"]}],
  ["Write thanks and confirm the meeting time in the reply", "Reply", "text", {"not":  ["thanks"], "cliNone":  true}],
  ["Reply with we will review and approve it", "Reply", "text", {"not":  ["we will review"], "cliNone":  true}],
  ["Answer with I will check and update the doc tomorrow", "Reply", "text", {"not":  ["I will check"], "cliNone":  true}],
  ["Reply to the thread with thanks I will read and share it with the team", "Reply", "text", {"not":  ["thanks I will read"]}],
  ["Type I will check and reply to you soon", "Message", "text", {"has":  ["I will check and reply to you soon"], "not":  ["I will check"]}],
  ["Type please sign and submit the form by Friday", "Message", "text", {"not":  ["please sign"]}],
  ["Type we shipped and hit our target", "Message", "text", {"has":  ["we shipped and hit our target"], "not":  ["we shipped"]}],
  ["Type the blog post and press release are ready", "Message", "text", {"has":  ["the blog post and press release are ready"], "not":  ["the blog post"]}],
  ["Type remember to save and submit your timesheet", "Message", "text", {"not":  ["remember to save"]}],
  ["Type we will finalize and send Monday", "Message", "text", {"has":  ["we will finalize and send Monday"], "not":  ["we will finalize"]}],
  ["Type Hi team please review and reply to the RFC", "Message", "text", {"not":  ["Hi team please review"]}],
  ["Write I will draft it and send it to you tomorrow", "Message", "text", {"not":  ["I will draft it"]}],
  ["Type we will test and pick a date tomorrow", "Message", "text", {"not":  ["we will test"]}],
  ["Type I will check and open the PR tomorrow", "Message", "text", {"not":  ["I will check"]}],
  ["Post a comment as we will fix and publish it tomorrow", "Comment", "text", {"not":  ["we will fix"]}],
  ["Set the note as I will check and update the doc tomorrow", "Note", "text", {"not":  ["I will check"]}],
  ["type a polite message that confirms our meeting on Tuesday and send it", "Message", "text", {"not":  ["a polite message that confirms our meeting on Tuesday and send it", "a polite message that confirms our meeting on Tuesday", "a polite message that confirms our meeting"]}],
  ["Search for Q3 Roadmap and open Licious", "Search", "search", {"has":  ["Q3 Roadmap", "Q3 Roadmap and open Licious"], "first":  ["Q3 Roadmap", "Q3 Roadmap and open Licious"]}],
  ["Search for how to start and stop Docker containers", "Search", "search", {"has":  ["how to start and stop Docker containers"]}],
  ["Look up how to install and run Python", "Search", "search", {"has":  ["how to install and run Python"]}],
  ["Create a task named Review and approve Q3 budget", "Name", "line", { has: ["Review and approve Q3 budget"], pluginHas: ["Review and approve Q3 budget"], notAlone: ["Review"] }],
  ["Add a to-do called Sign and return NDA", "Name", "line", { has: ["Sign and return NDA"], notAlone: ["Sign"] }],
  ["Save the view as Closed and open PRs", "Name", "line", { has: ["Closed and open PRs"], pluginHas: ["Closed and open PRs"], notAlone: ["Closed"] }],
  ["set the subject to Quarterly budget review for Q3 planning, then send it", "Subject", "line", {"not":  ["Quarterly budget review", "Quarterly"]}],
  ["Add an action with a short description of the follow-up on the API contract review, and assign it to Ann Lee", "What needs to be done?", "text", {"not":  ["a short description"]}],
  ["set the owner to Sarah Connor from the Berlin office", "Owner", "line", {"has":  ["Sarah Connor"]}],
  ["set the subject to A Note on Pricing", "Subject", "line", {"has":  ["A Note on Pricing"]}],
  ["Create a project called QA Regression Suite Nightly Run", "Project Name", "line", {"has":  ["QA Regression Suite Nightly Run"]}],
  ["Rename the meeting to Weekly Sync with Design Team", "Name", "line", {"not":  ["Weekly Sync"]}],
  ["Create a page named Onboarding Guide for New Hires", "Name", "line", {"pluginNot":  ["Onboarding Guide"]}],
  ["set my status to Out of office", "Status", "line", {"has":  ["Out of office"]}],
  ["Change the display name to Ann Marie Lee and save", "Display name", "line", {"has":  ["Ann Marie Lee"]}],
  ["Create a folder named Test Reports and open it", "Folder name", "line", {"has":  ["Test Reports"]}],  // Round 7 (F1): a UI label in quotes, backticks, bold, or brackets after "click" or "press" ends the value.
  ["Rename the file to budget and click \"Save\"", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and click \"Save\""], notAlone: ["Save"] }],
  ["Type hello and click \"Send\"", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["Send"] }],
  ["Type hello and press \"Enter\"", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["Enter"] }],
  ["Type hello and press “Enter”", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["Enter"] }],
  ["Reply with thanks and click \"Send\"", "Reply", "text", { has: ["thanks"], pluginHas: ["thanks"], notAlone: ["Send"] }],
  ["Reply with thanks and click 'Send'", "Reply", "text", { has: ["thanks"], pluginHas: ["thanks"], notAlone: ["Send"] }],
  ["Type LGTM and click \"Approve\"", "Comment", "text", { has: ["LGTM"], pluginHas: ["LGTM"], notAlone: ["Approve"] }],
  ["Set the status to Out of office and press \"Save\"", "Status", "line", { has: ["Out of office"], pluginHas: ["Out of office"], notAlone: ["Save", "Out"] }],
  ["Create a task named Fix login bug and click \"Create task\"", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], notAlone: ["Create task", "Fix"] }],
  ["Rename the file to budget and click `Save`", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and click `Save`"] }],
  ["Rename the file to budget and click **Save**", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and click **Save**"] }],
  ["Rename the file to budget and click [Save]", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and click [Save]"] }],
  ["Type hello and click (Send)", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and click (Send)", "hello and click (Send"] }],
  ["Type hello team and press **Enter**", "Message", "text", { has: ["hello team"], pluginHas: ["hello team"], not: ["hello team and press **Enter**"] }],
  ["Type thanks and press ⏎ Enter", "Message", "text", { has: ["thanks"], pluginHas: ["thanks"], not: ["thanks and press ⏎ Enter"], notAlone: ["Enter"] }],
  ["Type hello and click \"send\"", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["send"] }],
  ["Rename the file to budget and click \"save\"", "Name", "line", { has: ["budget"], pluginHas: ["budget"], notAlone: ["save"] }],
  // Round 7 (F2): "press the Enter key", "hit the Send button", and key chords end a message; a sentence keeps "hit the Q3 target".
  ["Type hello and press the Enter key", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and press the Enter key"], notAlone: ["key", "Enter"] }],
  ["Type hello team and hit the Send button", "Message", "text", { has: ["hello team"], pluginHas: ["hello team"], not: ["hello team and hit the Send button"], notAlone: ["Send"] }],
  ["Type ok and hit the return key", "Message", "text", { has: ["ok"], pluginHas: ["ok"], not: ["ok and hit the return key"] }],
  ["Type thanks and press the send button", "Message", "text", { has: ["thanks"], pluginHas: ["thanks"], not: ["thanks and press the send button"] }],
  ["Write thanks and press the Send button", "Message", "text", { has: ["thanks"], pluginHas: ["thanks"], not: ["thanks and press the Send button"], notAlone: ["Send"] }],
  ["Type hello and press the blue Send button", "Message", "text", { has: ["hello"], not: ["hello and press the blue Send button"] }],
  ["Type Berlin and press the down arrow", "City", "line", { has: ["Berlin"], not: ["Berlin and press the down arrow"] }],
  ["Enter Paris and hit the search button", "Destination", "line", { has: ["Paris"], not: ["Paris and hit the search button"], notAlone: ["button"] }],
  ["Type Paris and press the Enter key", "Search", "search", { has: ["Paris"], not: ["Paris and press the Enter key"], first: ["Paris", "key"] }],
  ["Type hello and press ctrl+enter", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and press ctrl+enter"] }],
  ["Rename the doc to budget and press cmd+s", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and press cmd+s"] }],
  ["Type we shipped and hit the Q3 target", "Message", "text", { has: ["we shipped and hit the Q3 target"], not: ["we shipped"] }],
  ["Type I worked late and hit the Friday deadline", "Message", "text", { has: ["I worked late and hit the Friday deadline"], not: ["I worked late"] }],
  ["Write we grew fast and hit the March goal", "Message", "text", { not: ["we grew fast"] }],
  // Round 7 (F3) and the round-7 lab: a maybe cut and its longer value are a pair. The head offers both when one passes.
  ["Set the title to Weekly sync and open Settings", "Title", "line", { has: ["Weekly sync"], pluginHas: ["Weekly sync"], first: ["Weekly sync", "Weekly sync and open Settings"], notAlone: ["Settings", "Weekly sync and open Settings"] }],
  ["Set the channel topic to Launch prep and open Settings", "Topic", "line", { has: ["Launch prep"], pluginHas: ["Launch prep"], first: ["Launch prep", "Launch prep and open Settings"], notAlone: ["Settings"], not: ["Launch"] }],
  ["Rename the board to Q3 Launch and open Settings", "Board name", "line", { has: ["Q3 Launch"], pluginHas: ["Q3 Launch"], first: ["Q3 Launch", "Q3 Launch and open Settings"], notAlone: ["Settings"] }],
  ["Rename the file to budget and go back to the folder", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and go back to the folder"], notAlone: ["the folder"] }],
  ["Set the title to Weekly sync and go back to the list", "Title", "line", { has: ["Weekly sync"], pluginHas: ["Weekly sync"], not: ["Weekly sync and go back to the list"], notAlone: ["the list"] }],
  ["Rename the channel to general chat and go back to Home", "Name", "line", { has: ["general chat"], pluginHas: ["general chat"], notAlone: ["Home"] }],
  ["Set the status to Out of office and go back to the dashboard", "Status", "line", { has: ["Out of office"], pluginHas: ["Out of office"], notAlone: ["the dashboard"] }],
  ["Change the display name to Ann Lee and save changes to the profile", "Display name", "line", { has: ["Ann Lee"], pluginHas: ["Ann Lee"], notAlone: ["the profile"] }],
  ["Rename the doc to budget and save changes before closing", "Name", "line", { has: ["budget"], pluginHas: ["budget"], first: ["budget", "budget and save changes before closing"] }],
  ["Change the name to Q3 plan and choose Private", "Name", "line", { has: ["Q3 plan"], pluginHas: ["Q3 plan"], notAlone: ["Private"] }],
  ["Set the title to Launch plan and mark Complete", "Title", "line", { has: ["Launch plan"], pluginHas: ["Launch plan"], notAlone: ["Complete"] }],
  ["Set the title to Team offsite and select High priority", "Title", "line", { has: ["Team offsite"], pluginHas: ["Team offsite"], notAlone: ["High"] }],
  ["Set the title to Weekly sync and check Remember me", "Title", "line", { has: ["Weekly sync"], pluginHas: ["Weekly sync"], notAlone: ["Remember"] }],
  ["Set the name to Acme Corp and toggle Dark mode", "Name", "line", { has: ["Acme Corp"], pluginHas: ["Acme Corp"], notAlone: ["Dark"] }],
  ["Set the title to Fix login bug and set Priority to High", "Title", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], not: ["Fix login bug and set Priority"], notAlone: ["High", "Priority", "Fix"] }],
  ["Set the subject to Lunch plans and send Ann an invite", "Subject", "line", { has: ["Lunch plans"], pluginHas: ["Lunch plans"], notAlone: ["Ann"] }],
  ["Fill the Name field with Q3 plan and select Public", "Name", "line", { has: ["Q3 plan"], pluginHas: ["Q3 plan"], notAlone: ["Public", "Name", "the Name field", "the Name field with Q3 plan"] }],
  ["Create a task named Review and approve changes to pricing", "Name", "line", { has: ["Review and approve changes to pricing"], pluginHas: ["Review and approve changes to pricing"], not: ["Review and approve changes"], notAlone: ["Review", "pricing"] }],
  ["Set the title to Review and approve Q3 budget", "Title", "line", { has: ["Review and approve Q3 budget"], pluginHas: ["Review and approve Q3 budget"], notAlone: ["Review"] }],
  ["Set the course name to Learn and use Python", "Name", "line", { has: ["Learn and use Python"], pluginHas: ["Learn and use Python"], notAlone: ["Learn"] }],
  ["Rename the sheet to Sales and update Totals", "Name", "line", { has: ["Sales", "Sales and update Totals"], first: ["Sales", "Sales and update Totals"] }],
  ["Set the title to Draft and share Q3 OKRs", "Title", "line", { has: ["Draft", "Draft and share Q3 OKRs"], first: ["Draft", "Draft and share Q3 OKRs"] }],
  ["Set the status to At lunch and check back at 2", "Status", "line", { has: ["At lunch", "At lunch and check back at 2"], pluginHas: ["At lunch"], first: ["At lunch", "At lunch and check back at 2"] }],
  ["Search the docs for how to install and run Python", "Search", "search", { has: ["how to install and run Python"] }],
  ["Search Google for how to install and use Figma", "Search", "search", { has: ["how to install and use Figma"] }],
  ["Search for invoices and open Stripe", "Search", "search", { has: ["invoices", "invoices and open Stripe"], first: ["invoices", "invoices and open Stripe"] }],
  ["Search the docs for how to create and delete API keys", "Search", "search", { has: ["how to create and delete API keys"] }],
  ["Create a folder named Reports and open Finance", "Folder name", "line", { has: ["Reports"], pluginHas: ["Reports"], first: ["Reports", "Reports and open Finance"], notAlone: ["Finance"] }],
  ["Rename the board to Sprint 12 and invite Ann Lee", "Board name", "line", { has: ["Sprint 12"], pluginHas: ["Sprint 12"], not: ["Sprint 12 and invite Ann Lee"], notAlone: ["Ann Lee", "12", "Sprint"] }],
  ["Create a workflow named Build and publish Release Notes", "Workflow name", "line", { has: ["Build and publish Release Notes"], pluginHas: ["Build and publish Release Notes"], notAlone: ["Build", "Release Notes"] }],
  ["Create a project named Plan and run Q4 offsite", "Project name", "line", { has: ["Plan and run Q4 offsite"], pluginHas: ["Plan and run Q4 offsite"], notAlone: ["Plan", "Q4"] }],
  ["Add a column called Blocked and move Card 12 to it", "Column name", "line", { has: ["Blocked"], pluginHas: ["Blocked"], not: ["Blocked and move Card 12"], notAlone: ["12", "it", "Card"] }],
  ["Type Looks good to me and send it to Priya", "Message", "text", { has: ["Looks good to me"], pluginHas: ["Looks good to me"], first: ["Looks good to me", "Looks good to me and send it to Priya"], notAlone: ["Priya", "me", "Looks good"] }],
  ["Write thanks for the update and post it to Design", "Message", "text", { has: ["thanks for the update"], pluginHas: ["thanks for the update"], first: ["thanks for the update", "thanks for the update and post it to Design"], not: ["thanks"], notAlone: ["the update", "Design"] }],
  // Round 7 (F4): a step verb before a lower-case task field and "to" or "as" ends the value; other lower-case objects give a maybe cut.
  ["Create a task named Fix login bug and set priority to High", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], not: ["Fix login bug and set priority to High", "Fix login bug and set priority"], notAlone: ["High", "Fix"] }],
  ["Create an issue titled Login fails on Safari and set priority to High", "Title", "line", { has: ["Login fails on Safari"], pluginHas: ["Login fails on Safari"], not: ["Login fails on Safari and set priority to High"], notAlone: ["High", "Login fails", "Login", "Safari"] }],
  ["Rename the task to Fix login bug and set status to In Progress", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], notAlone: ["In Progress", "Fix"] }],
  ["Create a task named Fix login bug and change status to Done", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], notAlone: ["Done"] }],
  ["Create a task named Fix login bug and set due date to Friday", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], notAlone: ["Friday"] }],
  ["Create a task named Fix login bug and assign ticket to Ann", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], first: ["Fix login bug", "Fix login bug and assign ticket to Ann"], notAlone: ["Ann"] }],
  ["Create a ticket titled Payment timeout and mark severity as critical", "Title", "line", { has: ["Payment timeout"], pluginHas: ["Payment timeout"], notAlone: ["critical"] }],
  ["Create a card called Update docs and move card to Done", "Name", "line", { has: ["Update docs", "Update docs and move card to Done"], pluginHas: ["Update docs"], first: ["Update docs", "Update docs and move card to Done"], notAlone: ["Done"] }],
  ["Create a task named Fix login bug and add label bug", "Name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"], first: ["Fix login bug", "Fix login bug and add label bug"] }],
  ["Search for how to copy and paste text to Excel", "Search", "search", { has: ["how to copy and paste text to Excel"] }],
  ["Search for how to set and change status to away", "Search", "search", { has: ["how to set and change status to away"] }],
  ["Create a doc titled How to create and share links to files", "Title", "line", { has: ["How to create and share links to files"] }],
  ["Create a task named Check and update status page", "Name", "line", { has: ["Check and update status page"] }],
  // Round 7 (F5): only a sentence dot ends a value, and a value that starts with a site ends at the "and" after it.
  ["Rename the file to report.pdf", "Name", "line", { has: ["report.pdf"], pluginHas: ["report.pdf"], not: ["report"] }],
  ["Rename the image to logo.png and click Save", "Name", "line", { has: ["logo.png"], not: ["logo", "logo.png and click Save"] }],
  ["Save the document as Q3-report.docx", "File name", "line", { has: ["Q3-report.docx"], first: ["Q3-report.docx", "Q3-report"] }],
  ["Set the file name to data.csv and click Upload", "File name", "line", { has: ["data.csv"], not: ["data", "data.csv and click Upload"] }],
  ["Save the file as notes.txt and close it", "File name", "line", { has: ["notes.txt"], not: ["notes"] }],
  ["Rename the file to Q3 Report v2.1 and click Save", "Name", "line", { has: ["Q3 Report v2.1"], not: ["Q3 Report v2"] }],
  ["Type Hello world. Then click Send", "Message", "text", { has: ["Hello world"], not: ["Hello world. Then click Send"] }],
  ["Type hello...and press Enter", "Message", "text", { has: ["hello"], not: ["hello...and press Enter"] }],
  ["Go to amazon.com and search for running shoes", "Search", "search", { has: ["running shoes"], not: ["amazon.com and search for running shoes", "amazon.com and search"] }],
  ["Go to example.com and type hello", "Message", "text", { has: ["hello"], not: ["example.com and type hello"] }],
  ["Go to https://example.com/login and type admin in the username field", "Username", "line", { has: ["admin"], not: ["https://example.com/login and type admin"] }],
  // Round 7 (F6): a message before "and send it to <someone>" or "and send it now" is a maybe cut, unless it is a sentence.
  ["Type hello and send it to the team", "Message", "text", { has: ["hello"], pluginHas: ["hello"], first: ["hello", "hello and send it to the team"], not: ["hello and send it"], notAlone: ["the team"] }],
  ["Type deploy done and post it to #general", "Message", "text", { has: ["deploy done"], pluginHas: ["deploy done"], first: ["deploy done", "deploy done and post it to #general"], not: ["deploy done and post it"], notAlone: ["#general"] }],
  ["Type hello and send the message to Ann", "Message", "text", { has: ["hello"], pluginHas: ["hello"], first: ["hello", "hello and send the message to Ann"], not: ["hello and send the message"], notAlone: ["Ann"] }],
  ["Type hello and send it now", "Message", "text", { has: ["hello"], pluginHas: ["hello"], first: ["hello", "hello and send it now"] }],
  ["Type Welcome aboard and send it to the new hire", "Message", "text", { has: ["Welcome aboard"], pluginHas: ["Welcome aboard"], notAlone: ["the new hire"] }],
  ["Type hello and send it to @ann", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["@ann"] }],
  ["Type hello and send to everyone", "Message", "text", { has: ["hello"], pluginHas: ["hello"], notAlone: ["everyone"] }],
  ["Write thanks and send it to Ann", "Message", "text", { has: ["thanks"], pluginHas: ["thanks"], notAlone: ["Ann"] }],
  ["Write hello team and post it to Engineering", "Message", "text", { has: ["hello team"], pluginHas: ["hello team"], notAlone: ["Engineering"] }],
  ["Write thanks and send it to the team", "Message", "text", { has: ["thanks"], pluginHas: ["thanks"], notAlone: ["the team"] }],
  ["Type thanks I will read and send it to the team", "Message", "text", { has: ["thanks I will read and send it to the team"], not: ["thanks I will read"] }],
  ["Type thanks we will finish and send it now", "Message", "text", { has: ["thanks we will finish and send it now"], not: ["thanks we will finish"] }],
  ["Type thanks and send it to you tomorrow", "Message", "text", { has: ["thanks and send it to you tomorrow"], not: ["thanks"] }],
  ["Type ok and reply to you soon", "Message", "text", { has: ["ok and reply to you soon"], not: ["ok"] }],
  ["Reply with I will check and reply to Ann", "Reply", "text", { not: ["I will check"] }],
  ["Type I love it and send it to Ann", "Message", "text", { has: ["I love it and send it to Ann"], not: ["I love it"] }],
  // Round 7 (F7): after type, a step that watches the reply ends the message.
  ["Type hello and wait for the response", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and wait for the response", "hello and wait"], notAlone: ["the response"] }],
  ["Type hello and wait for a reply", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and wait for a reply", "hello and wait"] }],
  ["Type hi and check the reply", "Message", "text", { has: ["hi"], pluginHas: ["hi"], not: ["hi and check the reply"] }],
  ["Type hi and check that the bot replies", "Message", "text", { has: ["hi"], pluginHas: ["hi"], not: ["hi and check that the bot replies"] }],
  ["Type hello and verify the bot responds", "Message", "text", { has: ["hello"], pluginHas: ["hello"], not: ["hello and verify the bot responds"] }],
  ["Type please restart and wait for the update to finish", "Message", "text", { has: ["please restart", "please restart and wait for the update to finish"], first: ["please restart", "please restart and wait for the update to finish"] }],
  ["Type hi and check the answer key", "Message", "text", { has: ["hi", "hi and check the answer key"], first: ["hi", "hi and check the answer key"] }],
  ["Type thanks and confirm the meeting time in the reply", "Reply", "text", { not: ["thanks"] }],
  ["Type please sign and confirm the booking by Friday", "Message", "text", { not: ["please sign"] }],
  ["Type please review and check the attached doc", "Message", "text", { not: ["please review"] }],
  ["Type I will check and wait for the reply", "Message", "text", { has: ["I will check and wait for the reply"], not: ["I will check"] }],
  ["Type thanks I will read and check the reply", "Message", "text", { has: ["thanks I will read and check the reply"], not: ["thanks I will read"] }],
  ["Search for how to deploy and verify a Lambda", "Search", "search", { has: ["how to deploy and verify a Lambda"] }],
  ["Set the title to Hurry up and wait", "Title", "line", { has: ["Hurry up and wait"], pluginHas: ["Hurry up and wait"] }],
  ["Create a task named Build and verify the release", "Name", "line", { has: ["Build and verify the release"], pluginHas: ["Build and verify the release"], notAlone: ["Build"] }],
  // Round 7 (F8): steps of a form flow (continue, verify, sign out, make sure) end a value or give a maybe cut.
  ["Set the nickname to ace and continue", "Nickname", "line", { has: ["ace"], pluginHas: ["ace"], first: ["ace", "ace and continue"] }],
  ["Set the workspace name to acme-qa and continue", "Name", "line", { has: ["acme-qa"], pluginHas: ["acme-qa"], first: ["acme-qa", "acme-qa and continue"] }],
  ["Set the title to weekly sync and continue", "Title", "line", { has: ["weekly sync"], pluginHas: ["weekly sync"], first: ["weekly sync", "weekly sync and continue"] }],
  ["Rename the file to budget and verify it", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and verify it"] }],
  ["Set the display name to ace and sign out", "Display name", "line", { has: ["ace"], pluginHas: ["ace"], not: ["ace and sign out"] }],
  ["Set the name to budget and apply", "Name", "line", { has: ["budget"], pluginHas: ["budget"], first: ["budget", "budget and apply"] }],
  ["Rename the file to draft and cancel", "Name", "line", { has: ["draft"], pluginHas: ["draft"], first: ["draft", "draft and cancel"] }],
  ["Rename the file to budget and download it", "Name", "line", { has: ["budget"], pluginHas: ["budget"], not: ["budget and download it"] }],
  ["Rename the file to budget and verify the new name", "Name", "line", { has: ["budget"], pluginHas: ["budget"], first: ["budget", "budget and verify the new name"] }],
  ["Set the title to weekly sync and make sure it is saved", "Title", "line", { has: ["weekly sync"], pluginHas: ["weekly sync"], not: ["weekly sync and make sure it is saved"] }],
  ["Rename the list to groceries and refresh the page", "Name", "line", { has: ["groceries"], pluginHas: ["groceries"], first: ["groceries", "groceries and refresh the page"] }],
  ["Change the bio to coffee lover and log out", "Bio", "text", { has: ["coffee lover"], pluginHas: ["coffee lover"], not: ["coffee lover and log out"] }],
  ["Search for how to pause and continue a download", "Search", "search", { has: ["how to pause and continue a download"] }],
  ["Search for how to install and make sure it works", "Search", "search", { has: ["how to install and make sure it works"] }],
  ["Add a task named review and sign the contract", "Name", "line", { has: ["review and sign the contract"], not: ["review"] }],
  ["Add a task named draft and edit the blog post", "Name", "line", { has: ["draft and edit the blog post"], pluginHas: ["draft and edit the blog post"], notAlone: ["draft"] }],
  ["Set the subject to Deploy and verify the fix", "Subject", "line", { has: ["Deploy and verify the fix"], pluginHas: ["Deploy and verify the fix"], notAlone: ["Deploy"] }],
  // Round 7 (F9): the cuts of a value of more than 10 words are not offered in a field that can take new text.
  ["Type can you summarize the key points of the Q3 report for me", "Message", "text", { not: ["can you summarize the key points"] }],
  ["Type what are the opening hours of the Berlin store on weekends", "Message", "text", { not: ["what are the opening hours"] }],
  ["Type what is the capital of France and wait for the answer", "Message", "text", { has: ["what is the capital of France"], first: ["what is the capital of France", "what is the capital"], pluginNot: ["what is the capital"], notAlone: ["what is the capital"] }],
  ["Create a task named Fix the login bug of the mobile app that crashes after two failed attempts", "Name", "line", { not: ["Fix the login bug", "Fix"] }],
  ["Search for machine learning engineer jobs in Berlin that allow remote work and pay well", "Search", "search", { has: ["machine learning engineer jobs"] }],
  ["enter John Smith from the Berlin office who leads the QA team for the mobile app", "Owner", "line", { has: ["John Smith"] }],
  // Round 7 (F10): a title with I or we before "and" is not a sentence; a sentence has a helping verb after the pronoun.
  ["Save the filter as Issues I reported and close it", "Name", "line", { has: ["Issues I reported"], pluginHas: ["Issues I reported"] }],
  ["Save the view as Bugs we fixed and share it", "Name", "line", { has: ["Bugs we fixed"], pluginHas: ["Bugs we fixed"] }],
  ["Name the playlist as Songs I like and close it", "Name", "line", { has: ["Songs I like"], pluginHas: ["Songs I like"] }],
  ["Save the doc as Phase I plan and close it", "Name", "line", { has: ["Phase I plan"], pluginHas: ["Phase I plan"] }],
  ["Save the search as Tickets I own and close the dialog", "Name", "line", { has: ["Tickets I own"] }],
  ["Save the filter as issues I reported and close it", "Name", "line", { has: ["issues I reported"] }],
  ["Create a filter with Issues I reported and close it", "Name", "line", { has: ["Issues I reported"] }],
  ["Reply with Thanks I will read and share it with the team", "Reply", "text", { not: ["Thanks I will read"] }],
  ["Reply with Sure we will review and approve it", "Reply", "text", { not: ["Sure we will review"], cliNone: true }],
  ["Reply with OK I'll review and approve it", "Reply", "text", { not: ["OK I'll review"], cliNone: true }],
  // Round 9: a two-word step before more words of a name is a maybe cut (a pair), not a sure cut.
  ["Create a test case called User can sign up and log in and click Save", "Test name", "line", { has: ["User can sign up and log in"], notAlone: ["User can sign up"] }],
  ["Create a test named Sign up and log in with Google", "Test name", "line", { has: ["Sign up and log in with Google"], notAlone: ["Sign up"] }],
  ["Create a test case titled Session expires after log in and log out", "Title", "line", { has: ["Session expires after log in and log out"], notAlone: ["Session expires after log in"] }],
  ["Create a test named Admin can log in and log out", "Test name", "line", { has: ["Admin can log in and log out"] }],
  ["Create a reminder called Pack bags and make sure passports are ready", "Reminder", "line", { has: ["Pack bags and make sure passports are ready"], notAlone: ["Pack bags"] }],
  ["Set the title to Weekly sync and log out of the app", "Title", "line", { has: ["Weekly sync"], first: ["Weekly sync", "Weekly sync and log out of the app"] }],
  // Round 9: the words before the first "and" of a long value stay a value.
  ["Assign the bug to Priya and leave a note that the crash only happens on older Android phones", "Assignee", "line", { has: ["Priya"], pluginHas: ["Priya"] }],
  ["Rename the workspace to Acme and reload the page to confirm the new name persists after a refresh", "Workspace name", "line", { has: ["Acme"], pluginHas: ["Acme"] }],
  ["Create a new branch called feature-login from main and switch to it to confirm the branch shows up in the list", "Branch", "line", { has: ["feature-login"] }],
  ["Type can you summarize the key points of the Q3 report for me", "Message", "text", { not: ["can you summarize the key points"] }],
  // Round 9: a maybe cut whose longer value holds a quote mark is offered alone.
  ['Create a task named Fix login bug and choose "High"', "Task name", "line", { has: ["Fix login bug"], pluginHas: ["Fix login bug"] }],
  ['Set the channel topic to Launch prep and select "Private"', "Topic", "line", { has: ["Launch prep"] }],
  ['Set the title to Weekly sync and open "Settings"', "Title", "line", { has: ["Weekly sync"] }],
  ['Type hello and send it to "Design"', "Message", "text", { has: ["hello"] }],
  // Round 9: more ways to send a typed message are maybe cuts (a pair); a key chord with a dash is a chord.
  ["Type thanks and send it right away", "Message", "text", { has: ["thanks", "thanks and send it right away"], first: ["thanks", "thanks and send it right away"] }],
  ["Type hello team and post it in #general", "Message", "text", { has: ["hello team", "hello team and post it in #general"] }],
  ["Type Hello Ann and save it as a draft", "Message", "text", { has: ["Hello Ann", "Hello Ann and save it as a draft"] }],
  ["Type hello team and save the draft", "Message", "text", { has: ["hello team", "hello team and save the draft"] }],
  ["Type hello team and send your message", "Message", "text", { has: ["hello team"] }],
  ["Type hello team and share it", "Message", "text", { has: ["hello team"] }],
  ["Type hello world and use the Send button", "Message", "text", { has: ["hello world"] }],
  ["Type hello world and press ctrl-enter", "Message", "text", { has: ["hello world"] }],
  ["Type hello world and press cmd + enter", "Message", "text", { has: ["hello world"] }],
  ["Type we will review and send it over", "Message", "text", { has: ["we will review and send it over"] }],
  ["Type please sign and submit the form by Friday", "Message", "text", { has: ["please sign and submit the form by Friday"] }],
  // Round 9: "changes to" and "now to" after a step verb, and "back to" after a send verb, are maybe cuts.
  ["Add a task named Review and publish changes to the docs site and click Save", "Task name", "line", { has: ["Review and publish changes to the docs site"], pluginHas: ["Review and publish changes to the docs site"], first: ["Review", "Review and publish changes to the docs site"], not: ["Review and publish changes"], notAlone: ["Review", "the docs site"] }],
  ["Create a task named Update pricing and post changes to the blog", "Task name", "line", { has: ["Update pricing and post changes to the blog"], pluginHas: ["Update pricing and post changes to the blog"], notAlone: ["Update pricing", "the blog"] }],
  ["Create a task named Draft and send changes to legal", "Task name", "line", { has: ["Draft and send changes to legal"], pluginHas: ["Draft and send changes to legal"], notAlone: ["Draft", "legal"] }],
  ["Create a task named Review contract and send back to legal", "Task name", "line", { has: ["Review contract and send back to legal"], pluginHas: ["Review contract and send back to legal"], notAlone: ["Review contract", "legal"] }],
  ["Add a to-do named Proofread and post now to LinkedIn", "Task name", "line", { has: ["Proofread and post now to LinkedIn"], pluginHas: ["Proofread and post now to LinkedIn"], notAlone: ["Proofread", "LinkedIn"] }],
  // Round 9: a lead word or a kind of text after a message verb is a maybe cut: the value without it comes first.
  ["Type in hello world and press Enter", "Message", "text", { has: ["hello world"], first: ["hello world", "in hello world"], notAlone: ["in hello world"] }],
  ["Type the message Hello team and press Enter", "Message", "text", { has: ["Hello team"], notAlone: ["the message Hello team", "Hello"] }],
  ["Enter the text Looks good and click Comment", "Comment", "text", { has: ["Looks good"], notAlone: ["the text Looks good", "Looks"] }],
  ["Type in laptops and press Enter", "Search", "search", { has: ["laptops"] }],
  // Round 10: "share" at the end of a message is a maybe cut, and a sentence before it keeps it whole.
  ["Reply with thanks I will read and share it", "Reply", "text", { not: ["thanks I will read"] }],
  ["Type thanks I will read and share it", "Message", "text", { has: ["thanks I will read and share it"], not: ["thanks I will read"] }],
  ["Type I'll read and share", "Message", "text", { has: ["I'll read and share"], not: ["I'll read"] }],
  ["Type Please read and share", "Message", "text", { has: ["Please read", "Please read and share"], notAlone: ["Please read"] }],
  ["Type Like and share", "Message", "text", { has: ["Like", "Like and share"], notAlone: ["Like"] }],
  ["Type Please read and share, then click Comment", "Comment", "text", { has: ["Please read and share"], notAlone: ["Please read"] }],
  // Round 10: a maybe cut of a value of more than 10 words is offered alone.
  ["Set the title to Weekly sync and make sure the reminder toggle is turned on", "Title", "line", { has: ["Weekly sync"], pluginHas: ["Weekly sync"], first: ["Weekly sync", "Weekly"] }],
  ["Create a reminder called water plants and make sure the timer is set before we leave for the trip", "Reminder", "line", { has: ["water plants"], pluginHas: ["water plants"], first: ["water plants", "the trip"] }],
  ["Create a user named qa-bot and log in as that user to check that the dashboard loads", "Username", "line", { has: ["qa-bot"] }],
  // Round 10: the first words of a long title with an inner "and" before a noun stay a long cut.
  ["Create a ticket titled Crash and data loss when uploading large files from the mobile app", "Title", "line", { not: ["Crash"], cliNone: true }],
  ["Set the subject to Quarterly budget and headcount review for the leadership offsite next month", "Subject", "line", { not: ["Quarterly"], cliNone: true }],
  ["Create a ticket titled Login fails for SSO users and shows a blank page after the redirect", "Title", "line", { not: ["Login fails", "Login"], cliNone: true }],
  ["Set the subject to Review of Q3 budget and headcount for the leadership offsite next month", "Subject", "line", { not: ["Review"] }],
  // Round 10: a lead word counts only in lower case, and "out of" is not a lead.
  ["Type The text is too small and press Enter", "Reply", "text", { has: ["The text is too small"], not: ["is too small"] }],
  ["Type In Progress and press Enter", "Status", "line", { has: ["In Progress"], not: ["Progress"] }],
  ["Type Out of office and press Enter", "Status", "line", { has: ["Out of office"], not: ["of office"] }],
  ["Type out of stock and click Save", "Status", "line", { has: ["out of stock"], not: ["of stock"] }],
];

function heads(task: string, label: string, kind: Kind, canGenerate: boolean): string[] {
  const spans = extractSpans(task);
  const field = kind === "search" ? el("e1", "fill", label, "searchbox", { value: "", form: 1 })
    : el("e1", "fill", label, "textbox", { value: "", ...(kind === "text" ? {} : { inputType: "text" }), multiline: kind === "text", form: 1 });
  const page = obs("https://app.example/x", [field, el("e2", "click", "Save", "button", { form: 1 })], "page", { doc: 1 });
  const q = buildStep({ task, goal: "act", obs: page, history: [], spans, keys: [], bannedActionIds: new Set(), doneBanned: false, ...(canGenerate ? { canGenerate } : {}) }).questions["value_1"] as ChoiceQuestion | undefined;
  if (!q) return [];
  return Object.keys(q.criteria).filter((k) => k !== "none" && k !== "generate").map((k) => spans.find((s) => s.id === k)?.text ?? k);
}

describe("value heads for task wording from the review rounds", () => {
  it.each(CORPUS)("%s [%s, %s]", (task, label, kind, want) => {
    const cli = heads(task, label, kind, false);
    const plugin = heads(task, label, kind, true);
    for (const v of want.has ?? []) expect(cli).toContain(v);
    for (const v of want.not ?? []) { expect(cli).not.toContain(v); expect(plugin).not.toContain(v); }
    for (const v of want.pluginHas ?? []) expect(plugin).toContain(v);
    for (const v of want.pluginNot ?? []) expect(plugin).not.toContain(v);
    for (const v of want.notAlone ?? []) {
      for (const head of [cli, plugin]) if (head.includes(v)) expect(head).toEqual(expect.arrayContaining(want.has ?? []));
    }
    if (want.first) expect(cli.indexOf(want.first[0])).toBeLessThan(cli.indexOf(want.first[1]));
    if (want.cliNone) expect(cli).toEqual([]);
  });
});
